<?php

namespace Projects\PersonalWebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Projects\PersonalWebsiteBundle\Entity\category;


/**
 * categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryRepository extends EntityRepository
{
	public function getTotalRowCount()
	{
		return $this->getEntityManager()
			->createQuery('SELECT COUNT(a.id) FROM ProjectsPersonalWebsiteBundle:category a')
			->getSingleScalarResult();
	}
}
