<?php

namespace Projects\PersonalWebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * contentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contentRepository extends EntityRepository
{
}
