<?php

namespace Projects\PersonalWebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Projects\PersonalWebsiteBundle\Entity\language;


/**
 * languageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class languageRepository extends EntityRepository
{
}
