projects_personal_website_homepage:
    pattern:  /web/{name}
    defaults: { _controller: ProjectsPersonalWebsiteBundle:Home:index }

projects_personal_website_adminhomepage:
    pattern:  /admin/
    defaults: { _controller: ProjectsPersonalWebsiteBundle:HomeAdmin:index }

projects_personal_website_logoutadmin:
    pattern:  /admin/logout
    defaults: { _controller: ProjectsPersonalWebsiteBundle:HomeAdmin:logout }

projects_personal_website_displaysection:
    pattern:  /admin/displaysection/{section}
    defaults: { _controller: ProjectsPersonalWebsiteBundle:HomeAdmin:displaysection }